//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EurekaBank_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignado
    {
        public string chr_asigcodigo { get; set; }
        public string chr_sucucodigo { get; set; }
        public string chr_emplcodigo { get; set; }
        public System.DateTime dtt_asigfechaalta { get; set; }
        public Nullable<System.DateTime> dtt_asigfechabaja { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
