//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EurekaBank_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public string chr_cliecodigo { get; set; }
        public string vch_cliepaterno { get; set; }
        public string vch_cliematerno { get; set; }
        public string vch_clienombre { get; set; }
        public string chr_cliedni { get; set; }
        public string vch_clieciudad { get; set; }
        public string vch_cliedireccion { get; set; }
        public string vch_clietelefono { get; set; }
        public string vch_clieemail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuenta { get; set; }
    }
}
