//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EurekaBank_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public string chr_cuencodigo { get; set; }
        public string chr_monecodigo { get; set; }
        public string chr_sucucodigo { get; set; }
        public string chr_emplcreacuenta { get; set; }
        public string chr_cliecodigo { get; set; }
        public decimal dec_cuensaldo { get; set; }
        public System.DateTime dtt_cuenfechacreacion { get; set; }
        public string vch_cuenestado { get; set; }
        public int int_cuencontmov { get; set; }
        public string chr_cuenclave { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
