//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EurekaBank_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public string chr_cuencodigo { get; set; }
        public int int_movinumero { get; set; }
        public System.DateTime dtt_movifecha { get; set; }
        public string chr_emplcodigo { get; set; }
        public string chr_tipocodigo { get; set; }
        public decimal dec_moviimporte { get; set; }
        public string chr_cuenreferencia { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
}
