//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EurekaBank_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string chr_paracodigo { get; set; }
        public string vch_paradescripcion { get; set; }
        public string vch_paravalor { get; set; }
        public string vch_paraestado { get; set; }
    }
}
